[package]
name = "tytle_browser"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tytle = { path = "../tytle_core" }
wasm-bindgen = "0.2.39"
