[package]
name = "tytle-browser"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tytle-core = { path = "../tytle-core" }
wasm-bindgen = "0.2.39"
